const ignoredExercises: Record<string, string> = {
    "Cable Shoulder Press": "",
    "Chest Expansion": "",
    "Loop Band Single Arm Tricep Extension": "",
    "Loop Band Push Up": "",
    "Leg Pull-In": "",
    "Loop Band Good Morning": "",
    "Loop Band Glute Kickback": "",
    "Dumbbell Back Fly": "",
    "Dumbbell Squat To Shoulder Press": "",
    "Bench T-Spine Stretch": "",
    "Reach Behind and Open": "",
    "Cross-body Arm Stretch": "",
    "Seated Figure Four": "",
    "Knee to Chest Stretch": "",
    "Smith Machine Bent Over Row": "",
    "Smith Machine Glute Bridge": "",
    "PVC Shoulder External Rotation": "",
    "Couch Stretch": "",
    "Seated Forward Bend": "",
    "Wall Pectoral Stretch": "",
    "Tricep Stretch": "",
    "Pigeon Pose": "",
    "Single Leg Straight Forward Bend": "",
    "Lying Figure Four": "",
    "Lunge with Ankle Grab": "",
    "Squat with Rotation": "",
    "Freemotion Shoulder Press": "",
    "Crossover Standing Forward Bend": "",
    "Side Bend Stretch": "",
    "Up Dog": "",
    "Static Lunge": "",
    "Crab Pose": "",
    "Chin Drop": "",
    "Head Tilt": "",
    "Cable Wrist Curl": "",
    "Single Arm Preacher Curl": "",

    // ignored lazy
    "Standing Forward Bend": "",
    "Shin Box Quad": "",
    "Chest Doorway Stretch": "",
}

export const exerciseMappings: Record<string, string> = {
    "Barbell Incline Bench Press": "Incline Bench Press (Barbell)",
    "Dumbbell Incline Bench Press": "Incline Bench Press (Dumbbell)",
    "Smith Machine Incline Bench Press": "Incline Bench Press (Smith Machine)",
    "Smith Machine Bench Press": "Bench Press (Smith Machine)",
    "Dumbbell Bench Press": "Bench Press (Dumbbell)",
    "Barbell Bench Press": "Bench Press (Barbell)",
    "Machine Bench Press": "Chest Press (Machine)",
    "Dumbbell Pullover": "Pullover (Dumbbell)",
    "Dumbbell Decline Bench Press": "Decline Bench Press (Dumbbell)",
    "Barbell Decline Bench Press": "Decline Bench Press (Barbell)",
    "Standing Arnold Press": "Arnold Press (Dumbbell)",
    "Arnold Dumbbell Press": "Arnold Press (Dumbbell)",
    "Standing Dumbbell Shoulder Press": "Overhead Press (Dumbbell)",
    "Dumbbell Shoulder Press": "Overhead Press (Dumbbell)",
    "Seated Barbell Shoulder Press": "Seated Overhead Press (Barbell)",
    "Machine Shoulder Press": "Seated Shoulder Press (Machine)",
    "Barbell Shoulder Press": "Overhead Press (Barbell)",
    "Smith Machine Overhead Shoulder Press": "Overhead Press (Smith Machine)",
    "Dumbbell Skullcrusher": "Skullcrusher (Dumbbell)",
    "EZ-Bar Skullcrusher": "Skullcrusher (Barbell)",
    "Skullcrusher": "Skullcrusher (Dumbbell)",
    "Lat Pulldown": "Lat Pulldown (Cable)",
    "Machine Fly": "Chest Fly (Machine)",
    "Mid Cable Crossover Fly": "Cable Fly Crossovers",
    "Machine Rear Delt Fly": "Rear Delt Reverse Fly (Machine)",
    "Machine Leg Press": "Leg Press (Machine)",
    "Back Squat": "Squat (Barbell)",
    "Pause Back Squat": "Pause Squat (Barbell)",
    "Dumbbell Sumo Squat": "Sumo Squat (Dumbbell)",
    "Kettlebell Sumo Squat": "Sumo Squat (Kettlebell)",
    "Leg Extension": "Leg Extension (Machine)",
    "Seated Leg Curl": "Seated Leg Curl (Machine)",
    "Leg Curl": "Lying Leg Curl (Machine)",
    "Machine Hip Abductor": "Hip Abduction (Machine)",
    "Machine Tigh Abductor": "Hip Abduction (Machine)",
    "Machine Hip Adductor": "Hip Adduction (Machine)",
    "Calf Press": "Calf Press (Machine)",
    "Seated Machine Calf Press": "Calf Press (Machine)",
    "Standing Calf Press": "Calf Press (Machine)",
    "Dumbbell Lunge": "Lunge (Dumbbell)",
    "Barbell Lunge": "Lunge (Barbell)",
    "Side Lunge": "Lateral Lunge",
    "EZ-Bar Curl": "EZ Bar Biceps Curl",
    "Close-Grip EZ-Bar Curl": "EZ Bar Biceps Curl",
    "Cable Rope Tricep Extension": "Triceps Rope Pushdown",
    "Cable Tricep Extension": "Triceps Rope Pushdown",
    "Triceps Pressdown": "Triceps Pushdown",
    "Bent Over Barbell Row": "Bent Over Row (Barbell)",
    "Cable Row": "Seated Cable Row - Bar Grip",
    "Cable Row with Squat": "Squat Row",
    "Cable Upright Row": "Upright Row (Cable)",
    "T-Bar Row": "T Bar Row",
    "Machine Row": "Seated Row (Machine)",
    "Straight-Arm Pulldown": "Rope Straight Arm Pulldown",
    "Hammerstrength Iso Row": "Iso-Lateral Row (Machine)",
    "Dumbbell Shrug": "Shrug (Dumbbell)",
    "Barbell Shrug": "Shrug (Barbell)",
    "Cable Shrug": "Shrug (Cable)",
    "Lateral Raise": "Lateral Raise (Dumbbell)",
    "Side Lateral Raise": "Lateral Raise (Dumbbell)",
    "Cable Lateral Raise": "Lateral Raise (Cable)",
    "Machine Lateral Raise": "Lateral Raise (Machine)",
    "Smith Machine Shrug": "Shrug (Smith Machine)",
    "Smith Machine Behind the Back Shrug Shrug": "Shrug (Smith Machine)",
    "Deadlift": "Deadlift (Barbell)",
    "Romanian Deadlift": "Romanian Deadlift (Barbell)",
    "Dumbbell Romanian Deadlift": "Romanian Deadlift (Dumbbell)",
    "Low Cable Chest Fly": "Low Cable Fly Crossovers",
    "Cable Crossover Fly": "Cable Fly Crossovers",
    "Dumbbell Incline Fly": "Incline Chest Fly (Dumbbell)",
    "Dumbbell Bicep Curl": "Bicep Curl (Dumbbell)",
    "Cable Bicep Curl": "Bicep Curl (Cable)",
    "Barbell Curl": "Bicep Curl (Barbell)",
    "Dumbbell Preacher Curl": "Preacher Curl (Dumbbell)",
    "Preacher Curl": "Preacher Curl (Barbell)",
    "Machine Preacher Curl": "Preacher Curl (Machine)",
    "Crunches": "Crunch",
    "Dumbbell Walking Lunge": "Walking Lunge (Dumbell)",
    "Plank": "Plank",
    "Cycling": "Cycling",
    "Hip Thrust": "Hip Thrust",
    "Dip": "Triceps Dip",
    "Machine Tricep Dip": "Seated Dip Machine",
    "Palms-Up Dumbbell Wrist Curl": "Seated Palms Up Wrist Curl",
    "Hand Release Push Up": "Push Up",
    "Mini Loop Band Squat": "Squat (Band)",
    "Single Leg Hip Thrust": "Single Leg Hip Thrust",
    "Lunge Twist": "Twist",
    "Decline Crunch": "Decline Crunch",
    "Back Extensions": "Back Extensions (Hyperextension)",
    "Ab Crunch Machine": "Crunch (Machine)",
    "Hammerstrength Incline Chest Press": "Incline Chest Press (Machine)",
    "Loop Band Hammer Curl": "Hammer Curl (Band)",
    "Loop Band Deadlift": "Deadlift (Band)",
    "Loop Band Back Squat": "Squat (Band)",
    "Glute Kickback Machine": "Glute Kickback (Machine)",
    "Hammerstrength Decline Chest Press": "Decline Chest Press (Machine)",
    "Leg Press": "Leg Press (Machine)",
    "Push Up on Knees": "Kneeling Push Up",
    "Lunge": "Lunge",
    "Dumbbell Hip Thrust": "Hip Thrust (Barbell)", // warning on conversion
    "Dumbbell Fly": "Chest Fly (Dumbbell)",
    "Leg Raise": "Lying Leg Raise",
    "Incline Dumbbell Curl": "Seated Incline Curl (Dumbbell)",
    "Machine Bicep Curl": "Bicep Curl (Machine)",
    "Reverse Barbell Curl": "Reverse Curl (Barbell)",
    "Seated Dumbbell Curl": "Seated Incline Curl (Dumbbell)",
    "Dumbbell Shoulder Raise": "Lateral Raise (Dumbbell)",
    "Dumbbell Lateral Raise": "Lateral Raise (Dumbbell)",
    "Hammer Curls": "Hammer Curl (Dumbbell)",
    "Dumbbell Front Raise": "Front Raise (Dumbbell)",
    "Dumbbell Squat": "Squat (Dumbbell)",
    "Hammerstrength High Row": "Iso-Lateral High Row (Machine)",
    "Hack Squat": "Hack Squat (Machine)",
    "Dumbbell Row": "Dumbbell Row",
    "Russian Twist": "Russian Twist (Weighted)",
    "Hammerstrength Chest Press": "Iso-Lateral Chest Press (Machine)",
    "Machine Tricep Extension": "Triceps Extension (Machine)",
    "Lying Hamstrings Curl": "Lying Leg Curl (Machine)",
    "Seated Tricep Press": "Seated Tricep Press",
    "Dead Hang": "Dead Hang",
    "Cable Tricep Pushdown": "Triceps Pushdown",
    "Shoulder Press": "Shoulder Press (Dumbbell)",
    "Scissor Kick": "Ab Scissor",
    "Superman": "Superman",
    "Superman Hold": "Superman",
    "Superman with Scaption": "Superman",
    "Vertical Knee Raise": "Knee Raise Prallel Bars",
    "Cable Rear Delt Fly": "Rear Delt Reverse Fly (Cable)",
    "Seated Back Extension": "Back Extension (Machine)",
    "Bench Dip": "Bench Dip",
    "Assisted Pull Up": "Pull Up (Assisted)",
    "Palms-Down Dumbbell Wrist Curl": "Seated Palms Up Wrist Curl", // warning on conversion
    "Cable Rope Overhead Triceps Extension": "Triceps Rope Pushdown", // warning on conversion
    "Smith Machine Squat": "Squat (Smith Machine)",
    "Standing Machine Calf Raise": "Standing Calf Raise (Machine)",
    "Cable Crunch": "Cable Crunch",
    "Assisted Dip": "Tricep Dip (Assisted)",
    "Cycling - Stationary": "Cycling", // TODO look into this to conver properly the time in the csv
    "Running - Treadmill": "Treadmill", // and this
    "Vertical Leg Raise": "Leg Raise Paralled Bars",
    "Pendlay Row": "Pendlay Row (Barbell)",
    "Spider Curls": "Spider Curl (Dumbbell)",
    "Incline Dumbbell Row": "Chest Supported Incline Row (Dumbbell)",
    "Dumbbell Bulgarian Split Squat": "Bulgarian Split Squat",
    "Dumbbell Preacher Curls": "Preacher Curl (Dumbbell)",
    "Zottman Curl": "Zottman Curl (Dumbbell)",
    "Meadow Landmine Row": "Meadow Row (Barbell)",
    "Standing Machine Calf Press": "Standing Calf Raise (Machine)", // warning on conversion
    "Tricep Overhead Extension with Rope": "Triceps Extension (Carble)", // warning on conversion
    "Cable Shrugs": "Shrug (Cable)",
    "Hanging Leg Raise": "Hanging Leg Raise",
    "Single Arm Cable Bicep Curl": "Bicep Curl (Cable)",
    "Dumbbell Goblet Squat": "Goblet Squat",
    "Dead Bug": "Dead Bug",
    "Pull Up": "Pull Up",
    "Single Arm Row": "Dumbbell Row",
    "Tricep Kickback": "Triceps Kickback (Dumbbell)",
    "Bulgarian Split Squat": "Bulgarian Split Squat",
    "Chin Up": "Chin Up",
    "Diamond Push Up": "Diamond Push Up",
    "Cable One Arm Underhand Tricep Extension": "Single Arm Tricep Pushdown (Cable)",
    "Cable One Arm Tricep Side Extension": "Single Arm Tricep Pushdown (Cable)",
    "Single Arm Cable Crossover": "Single Arm Cable Crossover",
    "Cable Face Pull": "Face Pull",
    "Pike Push Up": "Pike Pushup",
    "Stiff-Legged Deadlift": "Straight Leg Deadlift",
    "Incline Back Extension": "Back Extension (Weighted Hyperextension)",
    "Front Squat": "Front Squat",
    "Single Arm Lat Pulldown": "Single Arm Lat Pulldown",

    // add a feature that alerts you when one of the ignored exercies is detected before conversion
    // add a warning that most of the streatching exercises are not available in hevy
    ...ignoredExercises
};
